/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

import static org.example.ListFunction.removeDuplicates;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println(removeDuplicates(new ArrayList<>())); // Returns []
        System.out.println(removeDuplicates(new ArrayList<>(List.of(1))));  // Returns [1]
        System.out.println(removeDuplicates(new ArrayList<>(List.of(1,2,3))));  // Returns [1, 2, 3]
        System.out.println(removeDuplicates(new ArrayList<>(List.of("A", "B", "B")))); // Returns ["A", "B"]
        System.out.println(removeDuplicates(new ArrayList<>(List.of(1, 1, 3, 3, 5, 5, 5)))); // Returns [1, 3, 5]
    }
}
